apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "application.name" . }}-deployment
  labels:
    app: {{ template "application.name" . }}
    chart: {{ template "application.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "application.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "application.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: argocd-acr-secret
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: Logging__LogLevel__Default
              value: Debug
            - name: Logging__LogLevel__Microsoft.AspNetCore
              value: Information
            - name: Interop.Api__PATH_BASE
              value: /{{ template "application.name" . }}
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
