apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "application.name" . }}-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "*.example.com"
    http:
      paths:
      - backend:
          service:
            name: {{ template "application.name" . }}-service
            port:
              name: http
        pathType: Prefix
        path: "/{{ template "application.name" . }}"
