apiVersion: v1
kind: Service
metadata:
  name: {{ template "application.name" . }}-service
  labels:
    app: {{ template "application.name" . }}
    chart: {{ template "application.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
  selector:
    app: {{ template "application.name" . }}
